#!/usr/bin/env bash

unset MSYS2WINFIRST
unset MSYSTEM
unset MSYSCON
unset MSYS2_PATH_TYPE
unset MSYSTEM_PREFIX
unset MSYSTEM_CARCH
unset MSYSTEM_CHOST
unset PROMPT
unset PATH

if [ "$#" == "1" ]; then
    TYPE=mingw64
else
    TYPE=$1
fi

~/scoop/apps/msys2/current/msys2_shell.cmd -$1 -defterm -here -no-start
